const solicitudesSeed = [
  {
    id: 'TP-0001',
    descripcion: 'Traslado de personal de mantenimiento a Planta A',
    origen: 'Sede Central',
    descripcionOrigen: 'Área de operaciones',
    destino: 'Planta A',
    descripcionDestino: 'Muelle principal',
    fechaInicio: new Date().toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
    organizacionCcOi: 'CC001',
    multiplesCcOi: [{ ccOi: 'CC001', porcentaje: 100 }],
    lunes: true,
    martes: false,
    miercoles: false,
    jueves: false,
    viernes: false,
    sabado: false,
    domingo: false,
    cantidadPasajeros: 8,
    tipoServicio: 'Transporte de personal ocasional',
    gerencia: 'Gerencia A',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Leonardo',
    cedulaSolicitante: 'V-10000001',
    tipoSolicitud: 'Transporte de Personal',
    subtipo: 'Ocasional',
    nivelAprobacion: '1',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'TP-0002',
    descripcion: 'Transporte habitual de supervisores a Planta A',
    origen: 'Sede Central',
    descripcionOrigen: 'Oficinas administrativas',
    destino: 'Planta A',
    descripcionDestino: 'Sala de supervisión',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 4)).toISOString(),
    organizacionCcOi: 'CC002',
    multiplesCcOi: [{ ccOi: 'CC002', porcentaje: 100 }],
    lunes: true,
    martes: true,
    miercoles: false,
    jueves: false,
    viernes: false,
    sabado: false,
    domingo: false,
    cantidadPasajeros: 15,
    tipoServicio: 'Transporte de personal recurrente',
    gerencia: 'Gerencia A',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Leonardo',
    cedulaSolicitante: 'V-10000001',
    tipoSolicitud: 'Transporte de Personal',
    subtipo: 'Recurrente',
    nivelAprobacion: '2',
    estado: 'pendiente',
    motivoRechazo: null,
    modserv: '0001',
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'TP-0003',
    descripcion: 'Entrega urgente de personal al muelle norte',
    origen: 'Sede Central',
    descripcionOrigen: 'Recepción',
    destino: 'Muelle Norte',
    descripcionDestino: 'Zona de carga',
    fechaInicio: new Date(new Date().setHours(new Date().getHours() + 10)).toISOString(),
    fechaFin: new Date(new Date().setHours(new Date().getHours() + 12)).toISOString(),
    organizacionCcOi: 'CC003',
    multiplesCcOi: [{ ccOi: 'CC003', porcentaje: 100 }],
    lunes: false,
    martes: false,
    miercoles: false,
    jueves: true,
    viernes: false,
    sabado: false,
    domingo: false,
    cantidadPasajeros: 5,
    tipoServicio: 'Transporte de personal ocasional',
    gerencia: 'Gerencia A',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Leonardo',
    cedulaSolicitante: 'V-10000001',
    tipoSolicitud: 'Transporte de Personal',
    subtipo: 'Ocasional',
    nivelAprobacion: '1',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'OUM-0001',
    descripcion: 'Movimiento de grúa pesada a obra local',
    origen: 'Depósito Central',
    descripcionOrigen: 'Área de equipos pesados',
    destino: 'Sitio de Construcción A',
    descripcionDestino: 'Zona de obras civiles',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 12)).toISOString(),
    organizacionCcOi: 'CC004',
    multiplesCcOi: [{ ccOi: 'CC004', porcentaje: 100 }],
    tipoServicio: 'Movimiento de unidades mayores',
    gerencia: 'Gerencia A',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Leonardo',
    cedulaSolicitante: 'V-10000001',
    tipoSolicitud: 'Movimiento Unidades Mayores',
    subtipo: 'Ocasional',
    nivelAprobacion: '2',
    estado: 'pendiente',
    motivoRechazo: null,
    unidadMovilizar: 'Camión grúa 35t',
    descripcionUnidad: 'Camión grúa para traslado de maquinaria pesada',
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'SP-0001',
    descripcion: 'Suministro de repuestos eléctricos a Planta A',
    origen: 'Almacén Principal',
    descripcionOrigen: 'Depósito de piezas',
    destino: 'Planta A',
    descripcionDestino: 'Sala de mantenimiento',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 20)).toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 21)).toISOString(),
    organizacionCcOi: 'CC005',
    multiplesCcOi: [{ ccOi: 'CC005', porcentaje: 100 }],
    tipoServicio: 'Suministro lacustre',
    gerencia: 'Gerencia A',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Leonardo',
    cedulaSolicitante: 'V-10000001',
    tipoSolicitud: 'Suministro Lacustre',
    subtipo: null,
    nivelAprobacion: '3',
    estado: 'pendiente', 
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'TP-0004',
    descripcion: 'Transporte de técnicos de inspección a Planta B',
    origen: 'Sucursal Norte',
    descripcionOrigen: 'Área de cuadrillas',
    destino: 'Planta B',
    descripcionDestino: 'Taller de mantenimiento',
    fechaInicio: new Date().toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
    organizacionCcOi: 'CC006',
    multiplesCcOi: [{ ccOi: 'CC006', porcentaje: 100 }],
    lunes: false,
    martes: true,
    miercoles: true,
    jueves: false,
    viernes: false,
    sabado: false,
    domingo: false,
    cantidadPasajeros: 10,
    tipoServicio: 'Transporte de personal ocasional',
    gerencia: 'Gerencia B',
    aprobador: 'José',
    correo: 'jose@empresa.com',
    solicitante: 'Victoria',
    cedulaSolicitante: 'V-10000002',
    tipoSolicitud: 'Transporte de Personal',
    subtipo: 'Ocasional',
    nivelAprobacion: '1',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'TP-0005',
    descripcion: 'Transporte recurrente de personal técnico',
    origen: 'Sucursal Norte',
    descripcionOrigen: 'Oficinas técnicas',
    destino: 'Planta B',
    descripcionDestino: 'Sala de control',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    organizacionCcOi: 'CC007',
    multiplesCcOi: [{ ccOi: 'CC007', porcentaje: 100 }],
    lunes: true,
    martes: true,
    miercoles: true,
    jueves: false,
    viernes: false,
    sabado: false,
    domingo: false,
    cantidadPasajeros: 14,
    tipoServicio: 'Transporte de personal recurrente',
    gerencia: 'Gerencia B',
    aprobador: 'José',
    correo: 'jose@empresa.com',
    solicitante: 'Victoria',
    cedulaSolicitante: 'V-10000002',
    tipoSolicitud: 'Transporte de Personal',
    subtipo: 'Recurrente',
    nivelAprobacion: '2',
    estado: 'pendiente',
    motivoRechazo: null,
    modserv: '0002',
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'SP-0002',
    descripcion: 'Suministro de materiales de mantenimiento a Planta B',
    origen: 'Almacén Norte',
    descripcionOrigen: 'Depósito de herramientas',
    destino: 'Planta B',
    descripcionDestino: 'Área de servicios generales',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 22)).toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 23)).toISOString(),
    organizacionCcOi: 'CC008',
    multiplesCcOi: [{ ccOi: 'CC008', porcentaje: 100 }],
    tipoServicio: 'Suministro lacustre',
    gerencia: 'Gerencia B',
    aprobador: 'José',
    correo: 'jose@empresa.com',
    solicitante: 'Victoria',
    cedulaSolicitante: 'V-10000002',
    tipoSolicitud: 'Suministro Lacustre',
    subtipo: null,
    nivelAprobacion: '3',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'TO-0001',
    descripcion: 'Servicios portuarios de carga a Planta B',
    origen: 'Puerto Norte',
    descripcionOrigen: 'Muelle de carga',
    destino: 'Planta B',
    descripcionDestino: 'Zona de descarga',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 18)).toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 19)).toISOString(),
    organizacionCcOi: 'CC009',
    multiplesCcOi: [{ ccOi: 'CC009', porcentaje: 100 }],
    tipoServicio: 'Servicios portuarios',
    gerencia: 'Gerencia B',
    aprobador: 'José',
    correo: 'jose@empresa.com',
    solicitante: 'Victoria',
    cedulaSolicitante: 'V-10000002',
    tipoSolicitud: 'Servicios Portuarios',
    subtipo: null,
    nivelAprobacion: '3',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'SP-0004',
    descripcion: 'Suministro de insumos críticos a Planta B',
    origen: 'Almacén Norte',
    descripcionOrigen: 'Depósito de insumos',
    destino: 'Planta B',
    descripcionDestino: 'Área de producción',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    organizacionCcOi: 'CC015',
    multiplesCcOi: [{ ccOi: 'CC015', porcentaje: 100 }],
    tipoServicio: 'Suministro lacustre',
    gerencia: 'Gerencia B',
    aprobador: 'José',
    correo: 'jose@empresa.com',
    solicitante: 'Victoria',
    cedulaSolicitante: 'V-10000002',
    tipoSolicitud: 'Suministro Lacustre',
    subtipo: null,
    nivelAprobacion: '2',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'TP-0006',
    descripcion: 'Transporte urgente de inspección a Planta C',
    origen: 'Sucursal Este',
    descripcionOrigen: 'Recepción de mantenimiento',
    destino: 'Planta C',
    descripcionDestino: 'Área técnica',
    fechaInicio: new Date().toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
    organizacionCcOi: 'CC010',
    multiplesCcOi: [{ ccOi: 'CC010', porcentaje: 100 }],
    lunes: true,
    martes: false,
    miercoles: false,
    jueves: false,
    viernes: false,
    sabado: false,
    domingo: false,
    cantidadPasajeros: 6,
    tipoServicio: 'Transporte de personal ocasional',
    gerencia: 'Gerencia C',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Mary',
    cedulaSolicitante: 'V-10000003',
    tipoSolicitud: 'Transporte de Personal',
    subtipo: 'Ocasional',
    nivelAprobacion: '1',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'TP-0007',
    descripcion: 'Transporte de personal técnico a Planta C',
    origen: 'Sucursal Este',
    descripcionOrigen: 'Oficinas de planta',
    destino: 'Planta C',
    descripcionDestino: 'Sala de control',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 9)).toISOString(),
    organizacionCcOi: 'CC011',
    multiplesCcOi: [{ ccOi: 'CC011', porcentaje: 100 }],
    lunes: true,
    martes: true,
    miercoles: false,
    jueves: false,
    viernes: false,
    sabado: false,
    domingo: false,
    cantidadPasajeros: 7,
    tipoServicio: 'Transporte de personal ocasional',
    gerencia: 'Gerencia C',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Mary',
    cedulaSolicitante: 'V-10000003',
    tipoSolicitud: 'Transporte de Personal',
    subtipo: 'Ocasional',
    nivelAprobacion: '2',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'SP-0003',
    descripcion: 'Suministro de repuestos hidráulicos a Planta C',
    origen: 'Depósito Este',
    descripcionOrigen: 'Bodega de repuestos',
    destino: 'Planta C',
    descripcionDestino: 'Zona de mantenimiento',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    fechaFin: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    organizacionCcOi: 'CC012',
    multiplesCcOi: [{ ccOi: 'CC012', porcentaje: 100 }],
    tipoServicio: 'Suministro lacustre',
    gerencia: 'Gerencia C',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Mary',
    cedulaSolicitante: 'V-10000003',
    tipoSolicitud: 'Suministro Lacustre',
    subtipo: null,
    nivelAprobacion: '2',
    estado: 'pendiente',
    motivoRechazo: null,
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'OUM-0002',
    descripcion: 'Movimiento de generador a Planta C',
    origen: 'Taller Este',
    descripcionOrigen: 'Sala de energía',
    destino: 'Planta C',
    descripcionDestino: 'Sala de energía de planta',
    fechaInicio: new Date(new Date().setHours(new Date().getHours() + 20)).toISOString(),
    organizacionCcOi: 'CC013',
    multiplesCcOi: [{ ccOi: 'CC013', porcentaje: 100 }],
    tipoServicio: 'Movimiento de unidades mayores',
    gerencia: 'Gerencia C',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Mary',
    cedulaSolicitante: 'V-10000003',
    tipoSolicitud: 'Movimiento Unidades Mayores',
    subtipo: 'Ocasional',
    nivelAprobacion: '1',
    estado: 'pendiente',
    motivoRechazo: null,
    unidadMovilizar: 'Generador 500kW',
    descripcionUnidad: 'Generador móvil para respaldo eléctrico',
    fecha: new Date().toISOString().split('T')[0]
  },
  {
    id: 'OUM-0003',
    descripcion: 'Movimiento de plataforma de carga a Planta C',
    origen: 'Taller Este',
    descripcionOrigen: 'Zona de equipos',
    destino: 'Planta C',
    descripcionDestino: 'Muelle interno',
    fechaInicio: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    organizacionCcOi: 'CC014',
    multiplesCcOi: [{ ccOi: 'CC014', porcentaje: 100 }],
    tipoServicio: 'Movimiento de unidades mayores',
    gerencia: 'Gerencia C',
    aprobador: 'Linda',
    correo: 'linda@empresa.com',
    solicitante: 'Mary',
    cedulaSolicitante: 'V-10000003',
    tipoSolicitud: 'Movimiento Unidades Mayores',
    subtipo: 'Ocasional',
    nivelAprobacion: '2',
    estado: 'pendiente',
    motivoRechazo: null,
    unidadMovilizar: 'Plataforma de carga',
    descripcionUnidad: 'Plataforma para traslado de contenedores',
    fecha: new Date().toISOString().split('T')[0]
  }
];

module.exports = { solicitudesSeed };
