const db = require("./src/db");
const WorkOrder = db.WorkOrder || db.Workorder;
const values = {
  rowstamp: "x",
  wonum: "WO863692",
  status: "PENDPROG",
  statusdate: new Date("2026-07-15T00:00:00-04:00"),
  worktype: "OUM",
  description: "X",
  location: "Y",
  pmnum: "41214190",
  estdur: 1,
  estlabhrs: 1,
  estmatcost: 0,
  estlabcost: 0,
  esttoolcost: 0,
  actlabhrs: 0,
  actmatcost: 0,
  actlabcost: 0,
  acttoolcost: 0,
  haschildren: "N",
  outlabcost: 0,
  outmatcost: 0,
  outtoolcost: 0,
  historyflag: "N",
  targstartdate: new Date("2026-07-15T07:00:00-04:00"),
  wopm1: "origen",
  wopm3: "destino",
  wopm5: "S",
  wol1: "desc",
  wo1: new Date("2026-07-15T00:00:00-04:00"),
  wolablnk: "SISTEMA",
  chargestore: "N",
  estservcost: 0,
  actservcost: 0,
  estatapprlabhrs: 0,
  estatapprlabcost: 0,
  estatapprmatcost: 0,
  estatapprtoolcost: 0,
  estatapprservcost: 0,
  hasfollowupwork: "N",
  wfactive: "N",
  viewwoasoper: "N",
  worklocation: "destino",
  glaccount: "10118A1A12",
  supervisor: "sup",
  reportedby: "rep",
};
const queryInterface = db.connOracle.getQueryInterface();
const sql = queryInterface.queryGenerator.insertQuery(
  WorkOrder.getTableName(),
  values,
  WorkOrder.rawAttributes,
);
console.log("query:", sql.query);
console.log("bind:", JSON.stringify(sql.bind, null, 2));
