exports.tipos = [
    { 'categoriaId': 1, 'tx_nombre': 'PAGO DE BECA' },
    { 'categoriaId': 1, 'tx_nombre': 'PAGO DE GUARDERIA' },
    { 'categoriaId': 1, 'tx_nombre': 'SOLICITUD DE BECA NUEVA' },
    { 'categoriaId': 1, 'tx_nombre': 'CANCELACION DE BECA' },
    { 'categoriaId': 1, 'tx_nombre': 'PLAN DE VIVIENDA' },
    { 'categoriaId': 1, 'tx_nombre': 'LIBERACION DE HIPOTECA' },
    { 'categoriaId': 2, 'tx_nombre': 'LIBERACION DE HIPOTECA' },
    { 'categoriaId': 3, 'tx_nombre': 'EVENTO FUNERARIO' },
    { 'categoriaId': 1, 'tx_nombre': 'HABERES DE FALLECIDO' },
    { 'categoriaId': 1, 'tx_nombre': 'CARTA DE TRABAJO' },
    { 'categoriaId': 1, 'tx_nombre': 'RECLAMOS B.S.A (ANTIGUA TEA)' },
    { 'categoriaId': 2, 'tx_nombre': 'RECLAMOS B.S.A (ANTIGUA TEA)' },
    { 'categoriaId': 1, 'tx_nombre': 'CONSULTA B.S.A (ANTIGUA TEA)' },
    { 'categoriaId': 2, 'tx_nombre': 'CONSULTA B.S.A (ANTIGUA TEA)' },
    { 'categoriaId': 2, 'tx_nombre': 'ACTUALIZACION DE FE DE VIDA' },
    { 'categoriaId': 2, 'tx_nombre': 'REGISTRO DE SOBREVIVIENTES' },
    { 'categoriaId': 1, 'tx_nombre': 'INCLUSION DE DEPENDIENTES' },
    { 'categoriaId': 2, 'tx_nombre': 'INCLUSION DE DEPENDIENTES' },
    { 'categoriaId': 1, 'tx_nombre': 'EXCLUSION DE DEPENDIENTES' },
    { 'categoriaId': 2, 'tx_nombre': 'EXCLUSION DE DEPENDIENTES' },
    { 'categoriaId': 2, 'tx_nombre': 'CONSULTAS / ASESORIAS JUBILADO' },
    { 'categoriaId': 1, 'tx_nombre': 'CONSUTAS / ASESORIAS ACTIVOS' },
    { 'categoriaId': 3, 'tx_nombre': 'SERVICIOS PREVIOS' },
    { 'categoriaId': 2, 'tx_nombre': 'RECLAMOS PENSION' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION DE PAGO 1456' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION DE JUBILACIONES' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION PAAV' },
    { 'categoriaId': 3, 'tx_nombre': 'ASESORIAS COMITÉ LABORAL' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION RECLAMOS B.S.A (ANTIGUA TEA)' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION SERVICIOS PREVIOS' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION PAAV' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION PAGO POR EVENTO FUNERARIO' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION HABERES DE FALLECIDO' },
    { 'categoriaId': 3, 'tx_nombre': 'REVISION DE VACACIONES' },
    { 'categoriaId': 1, 'tx_nombre': 'ASESORIAS NIVEL III' },
    { 'categoriaId': 2, 'tx_nombre': 'ASESORIAS NIVEL III' },
    { 'categoriaId': 1, 'tx_nombre': 'RECLAMOS NIVEL III' },
    { 'categoriaId': 2, 'tx_nombre': 'RECLAMOS NIVEL III' },
    { 'categoriaId': 1, 'tx_nombre': 'ASESORIAS NIVEL IV' },
    { 'categoriaId': 2, 'tx_nombre': 'ASESORIAS NIVEL IV' },
    { 'categoriaId': 1, 'tx_nombre': 'RECLAMOS NIVEL IV' },
    { 'categoriaId': 2, 'tx_nombre': 'RECLAMOS NIVEL IV' },
    { 'categoriaId': 1, 'tx_nombre': 'CASOS DERIVADOS LIDER' },
    { 'categoriaId': 2, 'tx_nombre': 'CASOS DERIVADOS LIDER' },
    { 'categoriaId': 3, 'tx_nombre': 'CASOS DERIVADOS LIDER' }
]