
//   CREATE TABLE "MAXIMO"."VALUELIST" 
//    (	"LISTNAME" VARCHAR2(18) NOT NULL ENABLE, 
// 	"VALUE" VARCHAR2(25) NOT NULL ENABLE, 
// 	"MAXVALUE" VARCHAR2(25), 
// 	"VALDESC" VARCHAR2(30), 
// 	"DEFAULTS" VARCHAR2(1), 
// 	"TYPE" NUMBER NOT NULL ENABLE, 
// 	"ROWSTAMP" VARCHAR2(40) NOT NULL ENABLE
//    ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
//   STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
//   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
//   TABLESPACE "MAXIMO_D01"


//   SELECT DBMS_METADATA.get_ddl('TABLE', 'VALUELIST', 'MAXIMO')FROM DUAL