const {
  buildBaseContext,
  formatOracleTimestampTz,
} = require("../baseParser");

// Construye los payloads para solicitudes de Movimiento de Unidades Mayores.
// Se usa un worktype diferente para que Oracle pueda distinguir este flujo del de transporte personal.
const buildMovimientoUnidadesMayoresPayloads = (solicitud, pmnum, wonum) => {
  const context = buildBaseContext(solicitud);
  const codigoTipoServicio = context.tipoServicio || "";

  console.log("[Oracle parser][TP] Context estructurado:", {
  IDENTIFICADORES:{
    PMNUM: pmnum,
    WONUM: wonum
  },
  solicitud: {
    id: context.solicitudId,
    descripcion: context.descripcion,
    tipoServicio: context.tipoServicio,
    tipoSolicitud: context.tipoSolicitud,
    modserv: context.modserv,
    glaccount: context.centroCostoCcOi,
    nivelAprobacion: context.nivelAprobacion,
    unidadMovilizar: context.unidadMovilizar,
    
  },
  personas: {
    solicitante: context.solicitante,
    cedulaSolicitante: context.cedulaSolicitante,
    aprobador: context.aprobador,
    cedulaAprobador: context.cedulaAprobador,
    gerencia: context.gerencia,
    organizacion: context.organizacionNombre,
    telefono: context.telefono,
    correo: context.correo,
    changeby: context.changeby,
  },
  ubicacion: {
    origen: context.origen,
    descripcionOrigen: context.descripcionOrigen,
    destino: context.destino,
    descripcionDestino: context.descripcionDestino,
    cantidadPasajeros: context.cantidadPasajeros,
  },
  fechas: {
    today: context.today,
    fechaInicio: context.fechaInicio,
    fechaFin: context.fechaFin,
    dias: context.dias,
  },
});


  return {
    // pmPayload: {
    //   pmnum,
    //   rowstamp: String(Date.now()),
    //   supervisor: context.cedulaAprobador,
    //   eqnum: context.unidadMovilizar,
    //   usetargetdate: "S",
    //   lastmeterreading: 0.0,
    //   frequency: 1,
    //   meterfrequency: 0.0,
    //   pmcounter: 0,
    //   priority: context.nivelAprobacion,
    //   jpseqinuse: "N",
    //   pm17: context.modserv,
    //   pm18: formatOracleTimestampTz(context.fechaInicio),
    //   changedate: context.today,
    //   changeby: context.correo,
    //   description: context.descripcion,
    //   pm6: context.origen,
    //   pm7: context.descripcionOrigen,
    //   pm8: context.destino,
    //   pm9: context.descripcionDestino,
    //   pm10: codigoTipoServicio,
    //   pm11: formatOracleTimestampTz(context.fechaInicio),
    //   firstdate: context.fechaInicio,
    //   nextdate: context.fechaInicio,
    //   lastcompdate: context.fechaFin,
    //   pm1: String(context.today.getFullYear()),
    //   pm2: context.cedulaSolicitante,
    //   pm3: context.solicitante,
    //   pm4: context.organizacionNombre,
    //   pm5: context.organizacionCodigo,
    //   glaccount: context.centroCostoCcOi,
    //   haschildren: "N",
    //   usefrequency: "S",
    //   frequnit: "MESES",
    //   meterfrequency2: 0.0,
    //   lastmeterreading2: 0.0,
    //   pmjp1: context.dias.lunes,
    //   pmjp2: context.dias.martes,
    //   pmjp3: context.dias.miercoles,
    //   pmjp4: context.dias.jueves,
    //   pmjp5: context.dias.viernes,
    //   pmjp6: context.dias.sabado,
    //   pmjp7: context.dias.domingo,
    //   pm12: context.cantidadPasajeros,
    //   pm13: context.aprobador,
    //   pm14: context.gerencia,
    //   pm16: context.telefono,
    //   pmjp8: context.solicitudId,
    //   wostatus: "PENDPROG",
    //   worktype: "MUM",
    //   overridemasterupd: "N",
    //   ismasterpm: "N",
    //   applymasterpmtoeq: "S",
    //   applymasterpmtoloc: "S",
    //   updtimebasedfreq: "S",
    //   updstartdate: "S",
    //   updmeter1: "S",
    //   updmeter2: "S",
    //   updjpsequence: "S",
    //   updextdate: "S",
    //   updseasonaldates: "S",
    // },
    oselPayload: {
      wonum,
      description: context.descripcion,
      worktype: "MUM",
      status: "PENDPROG",
      glaccount: context.centroCostoCcOi,
      worts1: context.organizacionNombre,
      wol3: context.destino,
      req: context.solicitudId,
      bandera: "1",
      correo: context.correo,
      pmnum,
    },
    wostatusPayload: {
      rowstamp: String(Date.now()),
      wonum,
      status: "PENDPROG",
      changedate: context.today,
      changeby: context.correo,
      memo: context.descripcion,
      glaccount: context.centroCostoCcOi,
    },
    workorderPayload: {
      rowstamp: String(Date.now()),
      wonum,
      status: "PENDPROG",
      statusdate: formatOracleTimestampTz(context.today),
      eqnum: context.unidadMovilizar,
      worktype: "MUM",
      description: context.descripcion,
      // location: context.origen,
      changedate: formatOracleTimestampTz(context.today),
      estdur: 1,
      estlabhrs: 1,
      estmatcost: 0,
      estlabcost: 0,
      esttoolcost: 0,
      actlabhrs: 0,
      actmatcost: 0,
      actlabcost: 0,
      acttoolcost: 0,
      haschildren: "N",
      outlabcost: 0,
      outmatcost: 0,
      outtoolcost: 0,
      historyflag: "S",
      wopriority: parseInt(context.nivelAprobacion, 10),
      targstartdate: formatOracleTimestampTz(context.fechaInicio),
      // targcompdate: formatOracleTimestampTz(context.fechaInicio),
      wopm1: context.origen,
      wopm2: context.descripcionOrigen,
      wopm3: context.destino,
      wopm4: context.descripcionDestino,
      wopm5: codigoTipoServicio,
      // wopm6: context.modserv,
      wol1: context.organizacionNombre,
      wol2: "SOT", // PRUEBA A VER QUE HACE NO TODOS LO LLEVAN
      wo1: formatOracleTimestampTz(context.fechaInicio),
      wo10: context.aprobador,
      wolablnk: context.cedulaSolicitante,
      chargestore: "N",
      estservcost: 0,
      actservcost: 0,
      estatapprlabhrs: 0,
      estatapprlabcost: 0,
      estatapprmatcost: 0,
      estatapprtoolcost: 0,
      estatapprservcost: 0,
      hasfollowupwork: "N",
      wfactive: "N",
      viewwoasoper: "N",
      // worklocation: context.origen,
      woeq13: codigoTipoServicio,
      glaccount: context.centroCostoCcOi,
      supervisor: context.cedulaAprobador,
      // reportedby: context.correo,
      phone: context.telefono,
      worts1: context.organizacionNombre,
      // changeby: context.correo,
      wol3: context.solicitante,
      wo12: context.unidadMovilizar,
      reportdate: formatOracleTimestampTz(context.today)
    },
  };
};

module.exports = {
  buildMovimientoUnidadesMayoresPayloads,
};
