const {
  buildBaseContext,
  formatOracleDate,
  formatOracleTimestampTz,
} = require("../baseParser");

// Construye los payloads para solicitudes de Suministro Lacustre.
// Esta separación permite adaptar el mapeo sin afectar a los demás tipos de solicitud.
const buildSuministroLacustrePayloads = (solicitud, pmnum, wonum) => {
  const context = buildBaseContext(solicitud);

  return {
    pmPayload: {
      pmnum,
      rowstamp: String(Date.now()),
      supervisor: context.aprobador,
      usetargetdate: "S",
      lastmeterreading: 0.0,
      frequency: 1,
      meterfrequency: 0.0,
      pmcounter: 0,
      priority: 1,
      jpseqinuse: "N",
      pm17: "24X7",
      pm18: context.fechaInicio || context.today,
      changedate: context.today,
      changeby: context.changeby,
      description: context.descripcion,
      pm6: context.origen,
      pm7: context.descripcionOrigen,
      pm8: context.destino,
      pm9: context.descripcionDestino,
      pm10: context.modserv,
      firstdate: context.fechaInicio,
      nextdate: context.fechaInicio,
      lastcompdate: context.fechaFin,
      pm1: String(context.today.getFullYear()),
      pm2: context.organizacion,
      pm5: context.organizacion,
      glaccount: "10118A1A12",
      haschildren: "N",
      usefrequency: "S",
      frequnit: "MESES",
      meterfrequency2: 0.0,
      lastmeterreading2: 0.0,
      pmjp1: context.dias.lunes,
      pmjp2: context.dias.martes,
      pmjp3: context.dias.miercoles,
      pmjp4: context.dias.jueves,
      pmjp5: context.dias.viernes,
      pmjp6: context.dias.sabado,
      pmjp7: context.dias.domingo,
      pm12: context.cantidadPasajeros,
      pm13: context.aprobador,
      pm14: context.gerencia,
      pm16: context.cedulaSolicitante,
      pmjp8: "SR512085",
      wostatus: "PENDPROG",
      overridemasterupd: "N",
      ismasterpm: "N",
      applymasterpmtoeq: "S",
      applymasterpmtoloc: "S",
      updtimebasedfreq: "S",
      updstartdate: "S",
      updmeter1: "S",
      updmeter2: "S",
      updjpsequence: "S",
      updextdate: "S",
      updseasonaldates: "S",
    },
    oselPayload: {
      wonum,
      description: context.descripcion,
      worktype: "SL",
      status: "PENDPROG",
      glaccount: "10118A1A12",
      worts1: context.origen,
      wol3: context.destino,
      req: "N",
      bandera: "N",
      correo: context.correo,
      pmnum,
    },
    wostatusPayload: {
      rowstamp: String(Date.now()),
      wonum,
      status: "PENDPROG",
      changedate: context.today,
      changeby: context.changeby,
      memo: constext.descripcion,
      glaccount: "10118A1A12",
    },
    workorderPayload: {
      rowstamp: String(Date.now()),
      wonum,
      status: "PENDPROG",
      eqnum: null,
      statusdate: formatOracleDate(context.fechaInicio || context.today),
      worktype: "SL",
      description: context.descripcion,
      location: context.destino,
      pmnum,
      estdur: 1,
      estlabhrs: 1,
      estmatcost: 0,
      estlabcost: 0,
      esttoolcost: 0,
      actlabhrs: 0,
      actmatcost: 0,
      actlabcost: 0,
      acttoolcost: 0,
      haschildren: "N",
      outlabcost: 0,
      outmatcost: 0,
      outtoolcost: 0,
      historyflag: "N",
      targstartdate: formatOracleTimestampTz(
        context.fechaInicio || context.today,
      ),
      wopm1: context.origen,
      wopm3: context.destino,
      wopm5: "S",
      wol1: context.descripcion,
      wo1: formatOracleDate(context.fechaInicio || context.today),
      wolablnk: "SISTEMA",
      chargestore: "N",
      estservcost: 0,
      actservcost: 0,
      estatapprlabhrs: 0,
      estatapprlabcost: 0,
      estatapprmatcost: 0,
      estatapprtoolcost: 0,
      estatapprservcost: 0,
      hasfollowupwork: "N",
      wfactive: "N",
      viewwoasoper: "N",
      worklocation: context.destino,
      glaccount: "10118A1A12",
      supervisor: context.aprobador,
      reportedby: context.changeby,
    },
  };
};

module.exports = {
  buildSuministroLacustrePayloads,
};
